using ThroughlineBuild.Cli;
using ThroughlineBuild.Contracts;
using ThroughlineBuild.Scaffold;
using Tomlyn;
using Tomlyn.Model;
using Xunit;

namespace ThroughlineBuild.Cli.Tests;

public class ConfigProfileWriterTests
{
    // A trimmed copy of the .NET config template (the state 'build init' leaves behind):
    // dotnet checks, dotnet [project], plus comments in other sections to prove they survive.
    private const string DotnetConfig = """
    # Throughline Build configuration - generated by 'build init'
    [ticketing]
    backend = "plane"
    plane_base_url = "https://example.com"  # REQUIRED: set this

    [review]
    # Maximum time the verifier worker may run.
    verifier_timeout_minutes = 15

    # Each [[review.checks]] entry defines an automated check.
    [[review.checks]]
    # Human-readable name shown in verifier context.
    name = "build"
    executable = "dotnet"
    arguments = ["build", "--no-restore", "-c", "Release"]
    timeout_minutes = 5

    [[review.checks]]
    name = "test"
    executable = "dotnet"
    arguments = ["test", "--no-build", "-c", "Release"]
    timeout_minutes = 10

    # [ship] is optional - omit entirely to use defaults.
    [ship]
    remote = "origin"

    [[ship.regression_checks]]
    name = "build"
    executable = "dotnet"
    arguments = ["build"]
    timeout_minutes = 5

    [project]
    language = "csharp"
    framework = "dotnet"
    package_manager = "dotnet"
    build_command = "dotnet build"
    test_command = "dotnet test"
    install_command = "dotnet restore"
    dev_command = "dotnet run"
    workflow_tool = "build"
    plane_project_url = "https://plane.example.com/x/"
    """;

    private static ProjectProfile NpmProfile()
    {
        var checks = new[]
        {
            new ProfileCheck("build", "npm", new[] { "run", "build" }, 5),
            new ProfileCheck("test", "npm", new[] { "test" }, 10),
        };
        return new ProjectProfile(
            "typescript", "react-vite", "npm",
            "npm install", "npm run build", "npm test", "npm run dev",
            checks, checks);
    }

    [Fact]
    public void PristineDotnet_OverwrittenWithNpm()
    {
        var outcome = ConfigProfileWriter.Apply(DotnetConfig, NpmProfile(), force: false);

        Assert.True(outcome.Changed, outcome.SkipReason);
        Assert.NotNull(outcome.NewText);
        var text = outcome.NewText!;

        // Checks switched to npm; no dotnet anywhere anymore.
        Assert.Contains("executable = \"npm\"", text);
        Assert.Contains("arguments = [\"run\", \"build\"]", text);
        Assert.Contains("arguments = [\"test\"]", text);
        Assert.DoesNotContain("dotnet", text);

        // [project] re-derived.
        Assert.Contains("language = \"typescript\"", text);
        Assert.Contains("framework = \"react-vite\"", text);
        Assert.Contains("build_command = \"npm run build\"", text);
    }

    [Fact]
    public void PreservesOtherSectionsAndComments()
    {
        var text = ConfigProfileWriter.Apply(DotnetConfig, NpmProfile(), force: false).NewText!;

        // Untouched sections survive verbatim.
        Assert.Contains("backend = \"plane\"", text);
        Assert.Contains("plane_base_url = \"https://example.com\"  # REQUIRED: set this", text);
        Assert.Contains("verifier_timeout_minutes = 15", text);
        // Comments around the rewritten sections survive.
        Assert.Contains("# Each [[review.checks]] entry defines an automated check.", text);
        Assert.Contains("# [ship] is optional - omit entirely to use defaults.", text);
        // [project] keys the profile does not own are preserved.
        Assert.Contains("workflow_tool = \"build\"", text);
        Assert.Contains("plane_project_url = \"https://plane.example.com/x/\"", text);
    }

    [Fact]
    public void RewritesBothCheckArrays()
    {
        var text = ConfigProfileWriter.Apply(DotnetConfig, NpmProfile(), force: false).NewText!;
        // Two review checks + two regression checks, all npm. Count header LINES (a preserved
        // comment also mentions "[[review.checks]]", so a substring count would over-count).
        var reviewHeaders = HeaderLines(text, "[[review.checks]]");
        var shipHeaders = HeaderLines(text, "[[ship.regression_checks]]");
        Assert.Equal(2, reviewHeaders);
        Assert.Equal(2, shipHeaders);
    }

    [Fact]
    public void CustomizedChecks_SkippedWithoutForce()
    {
        var customized = DotnetConfig.Replace("executable = \"dotnet\"", "executable = \"make\"");
        var outcome = ConfigProfileWriter.Apply(customized, NpmProfile(), force: false);

        Assert.False(outcome.Changed);
        Assert.Null(outcome.NewText);
        Assert.Contains("customized", outcome.SkipReason);
    }

    [Fact]
    public void CustomizedChecks_OverwrittenWithForce()
    {
        var customized = DotnetConfig.Replace("executable = \"dotnet\"", "executable = \"make\"");
        var outcome = ConfigProfileWriter.Apply(customized, NpmProfile(), force: true);

        Assert.True(outcome.Changed);
        Assert.Contains("executable = \"npm\"", outcome.NewText!);
        Assert.DoesNotContain("make", outcome.NewText!);
    }

    [Fact]
    public void AlreadyConfiguredSkipReason_CustomizedChecks_ReturnsReason()
    {
        // A repo configured for a non-dotnet toolchain: derivation should be skipped before the
        // worker runs (the gate Apply would hit anyway). See TLB-491.
        var customized = DotnetConfig.Replace("executable = \"dotnet\"", "executable = \"npm\"");
        var reason = ConfigProfileWriter.AlreadyConfiguredSkipReason(customized, force: false);

        Assert.NotNull(reason);
        Assert.Contains("customized", reason);
        Assert.Contains("npm", reason);
    }

    [Fact]
    public void AlreadyConfiguredSkipReason_Force_ReturnsNull()
    {
        var customized = DotnetConfig.Replace("executable = \"dotnet\"", "executable = \"npm\"");
        Assert.Null(ConfigProfileWriter.AlreadyConfiguredSkipReason(customized, force: true));
    }

    [Fact]
    public void AlreadyConfiguredSkipReason_PristineDotnetTemplate_ReturnsNull()
    {
        // The dotnet template default is a replaceable placeholder, not a configured repo:
        // derivation must still run (e.g. to put npm checks into a fresh Node project).
        Assert.Null(ConfigProfileWriter.AlreadyConfiguredSkipReason(DotnetConfig, force: false));
    }

    [Fact]
    public void AlreadyConfiguredSkipReason_NoReviewChecks_ReturnsNull()
    {
        var noChecks = """
        [review]
        verifier_timeout_minutes = 15
        """;
        Assert.Null(ConfigProfileWriter.AlreadyConfiguredSkipReason(noChecks, force: false));
    }

    [Fact]
    public void Idempotent_SecondForcedApplyIsNoChange()
    {
        var first = ConfigProfileWriter.Apply(DotnetConfig, NpmProfile(), force: false);
        Assert.True(first.Changed);

        // Re-applying the same profile (force to bypass the now-"customized" npm gate) is a no-op.
        var second = ConfigProfileWriter.Apply(first.NewText!, NpmProfile(), force: true);
        Assert.False(second.Changed);
    }

    [Fact]
    public void NoProjectSection_AppendsOne()
    {
        var noProject = """
        [review]
        verifier_timeout_minutes = 15

        [[review.checks]]
        name = "build"
        executable = "dotnet"
        arguments = ["build"]
        timeout_minutes = 5
        """;
        var outcome = ConfigProfileWriter.Apply(noProject, NpmProfile(), force: false);
        Assert.True(outcome.Changed);
        Assert.Contains("[project]", outcome.NewText!);
        Assert.Contains("language = \"typescript\"", outcome.NewText!);
    }

    private static int HeaderLines(string text, string header) =>
        text.Split('\n').Count(l => l.Trim() == header);

    // A fully-loadable config (required [ticketing]) seeded with a dotnet review check so
    // Apply overwrites it. The canary round-trip test renders into this, then loads it back
    // through the real Config loader.
    private const string LoadableDotnetConfig = """
    [ticketing]
    backend = "plane"
    plane_base_url = "https://api.plane.so"
    plane_workspace_slug = "ws"
    plane_project_id = "abc-123"
    plane_api_token = "tok"

    [workers]
    default_agent = "claude-code"
    timeout_minutes = 30

    [workers.claude-code]
    executable = "claude"

    [workers.claude-code.sizes]
    small  = { model = "haiku" }
    medium = { model = "sonnet" }
    large  = { model = "opus" }

    [events]
    log_directory = ".build/events"

    [review]
    verifier_timeout_minutes = 15

    [[review.checks]]
    name = "build"
    executable = "dotnet"
    arguments = ["build"]
    timeout_minutes = 5

    [[ship.regression_checks]]
    name = "build"
    executable = "dotnet"
    arguments = ["build"]
    timeout_minutes = 5

    [project]
    language = "csharp"
    framework = "dotnet"
    package_manager = "dotnet"
    build_command = "dotnet build"
    test_command = "dotnet test"
    install_command = "dotnet restore"
    dev_command = "dotnet run"
    """;

    // The load-bearing escaping test: a canary whose content contains BOTH a double-quote
    // and a newline must survive ConfigProfileWriter render -> real Config loader parse
    // byte-for-byte. This is the case that breaks if TOML control-char escaping is wrong.
    [Fact]
    public void Canary_SurvivesRenderThenConfigLoad()
    {
        const string canaryPath = "src/probe/__tlb_probe.ts";
        const string canaryContent = "export const x: number = \"s\";\nlet y;";

        var canary = new[] { new CanaryFile(canaryPath, canaryContent) };
        var checks = new[]
        {
            new ProfileCheck("typecheck", "npm", new[] { "run", "typecheck" }, 5, canary),
        };
        var profile = new ProjectProfile(
            "typescript", "react-vite", "npm",
            "npm install", "npm run build", "npm test", "npm run dev",
            checks, checks);

        var outcome = ConfigProfileWriter.Apply(LoadableDotnetConfig, profile, force: false);
        Assert.True(outcome.Changed, outcome.SkipReason);
        var rendered = outcome.NewText!;

        // Sanity: the rendered TOML re-parses cleanly via Tomlyn (no raw control chars).
        var model = Toml.ToModel(rendered);
        Assert.NotNull(model);

        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        var path = Path.Combine(tmpDir, "config.toml");
        try
        {
            File.WriteAllText(path, rendered);
            var config = BuildConfigLoader.Load(path, warnSink: _ => { });

            var check = Assert.Single(config.Review.Checks);
            Assert.Equal("typecheck", check.Name);
            Assert.NotNull(check.Canary);
            var file = Assert.Single(check.Canary!);
            Assert.Equal(canaryPath, file.Path);
            Assert.Equal(canaryContent, file.Content);

            // The ship regression check carried the same canary; it must round-trip too.
            var shipCheck = Assert.Single(config.Ship.RegressionChecks);
            Assert.NotNull(shipCheck.Canary);
            Assert.Equal(canaryContent, Assert.Single(shipCheck.Canary!).Content);
        }
        finally
        {
            File.Delete(path);
            Directory.Delete(tmpDir, recursive: true);
        }
    }

    // convention_files renders into [project] as a string array and survives the real Config loader
    // back into ProjectContext.ConventionFiles. A path carrying a double-quote exercises the escaping.
    [Fact]
    public void ConventionFiles_SurviveRenderThenConfigLoad()
    {
        var conventionFiles = new[] { "src/setupTests.ts", "vite.config.ts", "src/weird\"name.ts" };
        var checks = new[] { new ProfileCheck("build", "npm", new[] { "run", "build" }, 5) };
        var profile = new ProjectProfile(
            "typescript", "react-vite", "npm",
            "npm install", "npm run build", "npm test", "npm run dev",
            checks, checks)
        {
            ConventionFiles = conventionFiles,
        };

        var outcome = ConfigProfileWriter.Apply(LoadableDotnetConfig, profile, force: false);
        Assert.True(outcome.Changed, outcome.SkipReason);
        var rendered = outcome.NewText!;
        Assert.Contains("convention_files = [", rendered);

        // Sanity: the rendered TOML re-parses cleanly via Tomlyn (escaping is valid).
        Assert.NotNull(Toml.ToModel(rendered));

        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        var path = Path.Combine(tmpDir, "config.toml");
        try
        {
            File.WriteAllText(path, rendered);
            var config = BuildConfigLoader.Load(path, warnSink: _ => { });
            Assert.Equal(conventionFiles, config.Project.ConventionFiles);
        }
        finally
        {
            File.Delete(path);
            Directory.Delete(tmpDir, recursive: true);
        }
    }

    // Apply into a config WITHOUT a [project] section appends one carrying the bundle.
    [Fact]
    public void ConventionFiles_AppendedWhenNoProjectSection()
    {
        var noProject = LoadableDotnetConfig[..LoadableDotnetConfig.IndexOf("[project]")].TrimEnd();
        var checks = new[] { new ProfileCheck("build", "npm", new[] { "run", "build" }, 5) };
        var profile = new ProjectProfile(
            "typescript", "react-vite", "npm",
            "npm install", "npm run build", "npm test", "npm run dev",
            checks, checks)
        {
            ConventionFiles = new[] { "conftest.py" },
        };

        var rendered = ConfigProfileWriter.Apply(noProject, profile, force: false).NewText!;
        Assert.Contains("[project]", rendered);
        Assert.Contains("convention_files = [\"conftest.py\"]", rendered);
        Assert.NotNull(Toml.ToModel(rendered));
    }

    // Empty bundle writes no convention_files line (no `convention_files = []` noise).
    [Fact]
    public void ConventionFiles_EmptyBundle_WritesNoLine()
    {
        var rendered = ConfigProfileWriter.Apply(LoadableDotnetConfig, NpmProfile(), force: false).NewText!;
        Assert.DoesNotContain("convention_files", rendered);
    }
}
