using ThroughlineBuild.Cli;
using ThroughlineBuild.Contracts;
using ThroughlineBuild.Scaffold;
using Tomlyn;
using Tomlyn.Model;
using Xunit;

namespace ThroughlineBuild.Cli.Tests;

public class ConfigProfileWriterTests
{
    // A config that already carries hand-written checks, plus comments in other sections to prove
    // they survive a rewrite. The executables happen to be dotnet; nothing in the writer may treat
    // that as special (TLB-639), so this fixture only ever exercises the overwrite path.
    private const string DotnetConfig = """
    # Throughline Build configuration - generated by 'build init'
    [ticketing]
    backend = "plane"
    plane_base_url = "https://example.com"  # REQUIRED: set this

    [review]
    # Maximum time the verifier worker may run.
    verifier_timeout_minutes = 15

    # Each [[review.checks]] entry defines an automated check.
    [[review.checks]]
    # Human-readable name shown in verifier context.
    name = "build"
    executable = "dotnet"
    arguments = ["build", "--no-restore", "-c", "Release"]
    timeout_minutes = 5

    [[review.checks]]
    name = "test"
    executable = "dotnet"
    arguments = ["test", "--no-build", "-c", "Release"]
    timeout_minutes = 10

    # [ship] is optional - omit entirely to use defaults.
    [ship]
    remote = "origin"

    [[ship.regression_checks]]
    name = "build"
    executable = "dotnet"
    arguments = ["build"]
    timeout_minutes = 5

    [project]
    language = "csharp"
    framework = "dotnet"
    package_manager = "dotnet"
    build_command = "dotnet build"
    test_command = "dotnet test"
    install_command = "dotnet restore"
    dev_command = "dotnet run"
    workflow_tool = "build"
    plane_project_url = "https://plane.example.com/x/"
    """;

    // What 'build init' actually leaves behind: a [review] section whose checks are all commented
    // out. This is the only state the writer may populate without an explicit override.
    private const string NoChecksConfig = """
    # Throughline Build configuration - generated by 'build init'
    [ticketing]
    backend = "plane"
    plane_base_url = "https://example.com"  # REQUIRED: set this

    [review]
    verifier_timeout_minutes = 15
    # Review checks are LEFT EMPTY on purpose - derived at install time.
    # [[review.checks]]
    # name = "build"
    # executable = "dotnet"

    [ship]
    remote = "origin"

    [project]
    language = ""
    framework = ""
    package_manager = ""
    build_command = ""
    test_command = ""
    install_command = ""
    dev_command = ""
    workflow_tool = "build"
    """;

    private static ProjectProfile NpmProfile()
    {
        var checks = new[]
        {
            new ProfileCheck("build", "npm", new[] { "run", "build" }, 5),
            new ProfileCheck("test", "npm", new[] { "test" }, 10),
        };
        return new ProjectProfile(
            "typescript", "react-vite", "npm",
            "npm install", "npm run build", "npm test", "npm run dev",
            checks, checks);
    }

    // One profile per toolchain, built from the executable name alone, so a test can assert the
    // writer behaves identically whatever the stack is.
    private static ProjectProfile ProfileFor(string executable, string buildCommand = "build")
    {
        var checks = new[] { new ProfileCheck("build", executable, new[] { "build" }, 5) };
        return new ProjectProfile(
            $"{executable}-lang", $"{executable}-stack", executable,
            $"{executable} install", $"{executable} {buildCommand}", $"{executable} test", $"{executable} dev",
            checks, checks);
    }

    [Fact]
    public void ExistingChecks_OverwrittenWithForce()
    {
        var outcome = ConfigProfileWriter.Apply(DotnetConfig, NpmProfile(), force: true);

        Assert.True(outcome.Changed, outcome.SkipReason);
        Assert.NotNull(outcome.NewText);
        var text = outcome.NewText!;

        // Checks switched to npm; no dotnet anywhere anymore.
        Assert.Contains("executable = \"npm\"", text);
        Assert.Contains("arguments = [\"run\", \"build\"]", text);
        Assert.Contains("arguments = [\"test\"]", text);
        Assert.DoesNotContain("dotnet", text);

        // [project] re-derived.
        Assert.Contains("language = \"typescript\"", text);
        Assert.Contains("framework = \"react-vite\"", text);
        Assert.Contains("build_command = \"npm run build\"", text);
    }

    // A config carrying no active checks - what 'build init' writes - is populated without an
    // override, on any stack.
    [Theory]
    [InlineData("dotnet")]
    [InlineData("go")]
    [InlineData("npm")]
    public void ConfigWithoutChecks_IsPopulatedWithoutForce(string executable)
    {
        var outcome = ConfigProfileWriter.Apply(NoChecksConfig, ProfileFor(executable), force: false);

        Assert.True(outcome.Changed, outcome.SkipReason);
        Assert.False(outcome.AlreadyMatched);
        Assert.True(HasActiveLine(outcome.NewText!, $"executable = \"{executable}\""));
    }

    // The fixture keeps commented-out template checks, so assertions about which executable is
    // configured must look at active lines only.
    private static bool HasActiveLine(string text, string line) =>
        text.Split('\n').Any(l => l.Trim() == line);

    [Fact]
    public void PreservesOtherSectionsAndComments()
    {
        var text = ConfigProfileWriter.Apply(DotnetConfig, NpmProfile(), force: true).NewText!;

        // Untouched sections survive verbatim.
        Assert.Contains("backend = \"plane\"", text);
        Assert.Contains("plane_base_url = \"https://example.com\"  # REQUIRED: set this", text);
        Assert.Contains("verifier_timeout_minutes = 15", text);
        // Comments around the rewritten sections survive.
        Assert.Contains("# Each [[review.checks]] entry defines an automated check.", text);
        Assert.Contains("# [ship] is optional - omit entirely to use defaults.", text);
        // [project] keys the profile does not own are preserved.
        Assert.Contains("workflow_tool = \"build\"", text);
        Assert.Contains("plane_project_url = \"https://plane.example.com/x/\"", text);
    }

    [Fact]
    public void RewritesBothCheckArrays()
    {
        var text = ConfigProfileWriter.Apply(DotnetConfig, NpmProfile(), force: true).NewText!;
        // Two review checks + two regression checks, all npm. Count header LINES (a preserved
        // comment also mentions "[[review.checks]]", so a substring count would over-count).
        var reviewHeaders = HeaderLines(text, "[[review.checks]]");
        var shipHeaders = HeaderLines(text, "[[ship.regression_checks]]");
        Assert.Equal(2, reviewHeaders);
        Assert.Equal(2, shipHeaders);
    }

    // TLB-491's protection, TLB-639's proxy: checks already in the config that say something other
    // than the profile were written by a human and are preserved. The old gate exempted "dotnet"
    // by name, so the dotnet case below fails the moment that literal comes back.
    [Theory]
    [InlineData("dotnet")]
    [InlineData("go")]
    [InlineData("make")]
    public void ExistingCheckThatDiffersFromProfile_IsGatedWhateverItsExecutable(string executable)
    {
        var existing = ConfigProfileWriter.Apply(NoChecksConfig, ProfileFor(executable), force: false).NewText!;

        var outcome = ConfigProfileWriter.Apply(existing, ProfileFor("npm"), force: false);

        Assert.False(outcome.Changed);
        Assert.False(outcome.AlreadyMatched);
        Assert.Null(outcome.NewText);
        Assert.Contains("customized", outcome.SkipReason);
        Assert.Contains("--force", outcome.SkipReason);
    }

    [Theory]
    [InlineData("dotnet")]
    [InlineData("go")]
    [InlineData("make")]
    public void ExistingCheckThatDiffersFromProfile_IsOverwrittenWithForce(string executable)
    {
        var existing = ConfigProfileWriter.Apply(NoChecksConfig, ProfileFor(executable), force: false).NewText!;

        var outcome = ConfigProfileWriter.Apply(existing, ProfileFor("npm"), force: true);

        Assert.True(outcome.Changed, outcome.SkipReason);
        Assert.True(HasActiveLine(outcome.NewText!, "executable = \"npm\""));
        Assert.False(HasActiveLine(outcome.NewText!, $"executable = \"{executable}\""));
    }

    // The install-stage-2 idempotence contract: re-applying the profile a repository is already
    // configured with is a no-op SUCCESS on every stack, and never reaches the clobber gate.
    [Theory]
    [InlineData("dotnet")]
    [InlineData("go")]
    [InlineData("npm")]
    [InlineData("swift")]
    public void SecondApplyOfSameProfile_IsIdempotentSuccessWithoutForce(string executable)
    {
        var profile = ProfileFor(executable);
        var first = ConfigProfileWriter.Apply(NoChecksConfig, profile, force: false);
        Assert.True(first.Changed, first.SkipReason);

        var second = ConfigProfileWriter.Apply(first.NewText!, profile, force: false);

        Assert.True(second.AlreadyMatched);
        Assert.False(second.Changed);
        Assert.Null(second.NewText);
        Assert.Null(second.SkipReason);
    }

    // The gate guards checks, not the whole file: a profile that keeps the checks byte-identical and
    // only moves a [project] key writes without an override.
    [Fact]
    public void ProjectKeyChangeAlone_DoesNotReachTheClobberGate()
    {
        var existing = ConfigProfileWriter.Apply(NoChecksConfig, ProfileFor("go"), force: false).NewText!;

        var outcome = ConfigProfileWriter.Apply(
            existing, ProfileFor("go", buildCommand: "build ./..."), force: false);

        Assert.True(outcome.Changed, outcome.SkipReason);
        Assert.Null(outcome.SkipReason);
        Assert.Contains("build_command = \"go build ./...\"", outcome.NewText!);
    }

    [Fact]
    public void NoProjectSection_AppendsOne()
    {
        var noProject = """
        [review]
        verifier_timeout_minutes = 15
        """;
        var outcome = ConfigProfileWriter.Apply(noProject, NpmProfile(), force: false);
        Assert.True(outcome.Changed, outcome.SkipReason);
        Assert.Contains("[project]", outcome.NewText!);
        Assert.Contains("language = \"typescript\"", outcome.NewText!);
    }

    private static int HeaderLines(string text, string header) =>
        text.Split('\n').Count(l => l.Trim() == header);

    // A fully-loadable config (required [ticketing]) seeded with an existing review check so Apply
    // overwrites it. Rendering tests below apply into it with force: true, because displacing checks
    // already in a config is exactly what the clobber gate exists to stop; what they assert is what
    // the writer RENDERS, which is identical either way. The canary round-trip test renders into
    // this, then loads it back through the real Config loader.
    private const string LoadableDotnetConfig = """
    [ticketing]
    backend = "plane"
    plane_base_url = "https://api.plane.so"
    plane_workspace_slug = "ws"
    plane_project_id = "abc-123"
    plane_api_token = "tok"

    [workers]
    default_agent = "claude-code"
    timeout_minutes = 30

    [workers.claude-code]
    executable = "claude"

    [workers.claude-code.sizes]
    small  = { model = "haiku" }
    medium = { model = "sonnet" }
    large  = { model = "opus" }

    [events]
    log_directory = ".build/events"

    [review]
    verifier_timeout_minutes = 15

    [[review.checks]]
    name = "build"
    executable = "dotnet"
    arguments = ["build"]
    timeout_minutes = 5

    [[ship.regression_checks]]
    name = "build"
    executable = "dotnet"
    arguments = ["build"]
    timeout_minutes = 5

    [project]
    language = "csharp"
    framework = "dotnet"
    package_manager = "dotnet"
    build_command = "dotnet build"
    test_command = "dotnet test"
    install_command = "dotnet restore"
    dev_command = "dotnet run"
    """;

    // The load-bearing escaping test: a canary whose content contains BOTH a double-quote
    // and a newline must survive ConfigProfileWriter render -> real Config loader parse
    // byte-for-byte. This is the case that breaks if TOML control-char escaping is wrong.
    [Fact]
    public void Canary_SurvivesRenderThenConfigLoad()
    {
        const string canaryPath = "src/probe/__tlb_probe.ts";
        const string canaryContent = "export const x: number = \"s\";\nlet y;";

        var canary = new[] { new CanaryFile(canaryPath, canaryContent) };
        var requiredPaths = new[] { "package.json", "src" };
        var checks = new[]
        {
            new ProfileCheck("typecheck", "npm", new[] { "run", "typecheck" }, 5,
                Canary: canary, RequiredPaths: requiredPaths),
        };
        var profile = new ProjectProfile(
            "typescript", "react-vite", "npm",
            "npm install", "npm run build", "npm test", "npm run dev",
            checks, checks);

        var outcome = ConfigProfileWriter.Apply(LoadableDotnetConfig, profile, force: true);
        Assert.True(outcome.Changed, outcome.SkipReason);
        var rendered = outcome.NewText!;

        // Sanity: the rendered TOML re-parses cleanly via Tomlyn (no raw control chars).
        var model = TomlSerializer.Deserialize<TomlTable>(rendered);
        Assert.NotNull(model);
        Assert.Contains("required_paths = [\"package.json\", \"src\"]", rendered);

        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        var path = Path.Combine(tmpDir, "config.toml");
        try
        {
            File.WriteAllText(path, rendered);
            var config = BuildConfigLoader.Load(path, warnSink: _ => { });

            var check = Assert.Single(config.Review.Checks);
            Assert.Equal("typecheck", check.Name);
            Assert.NotNull(check.Canary);
            var file = Assert.Single(check.Canary!);
            Assert.Equal(canaryPath, file.Path);
            Assert.Equal(canaryContent, file.Content);
            Assert.Equal(requiredPaths, check.RequiredPaths);

            // The ship regression check carried the same canary; it must round-trip too.
            var shipCheck = Assert.Single(config.Ship.RegressionChecks);
            Assert.NotNull(shipCheck.Canary);
            Assert.Equal(canaryContent, Assert.Single(shipCheck.Canary!).Content);
            Assert.Equal(requiredPaths, shipCheck.RequiredPaths);
        }
        finally
        {
            File.Delete(path);
            Directory.Delete(tmpDir, recursive: true);
        }
    }

    // convention_files renders into [project] as a string array and survives the real Config loader
    // back into ProjectContext.ConventionFiles. A path carrying a double-quote exercises the escaping.
    [Fact]
    public void ConventionFiles_SurviveRenderThenConfigLoad()
    {
        var conventionFiles = new[] { "src/setupTests.ts", "vite.config.ts", "src/weird\"name.ts" };
        var checks = new[] { new ProfileCheck("build", "npm", new[] { "run", "build" }, 5) };
        var profile = new ProjectProfile(
            "typescript", "react-vite", "npm",
            "npm install", "npm run build", "npm test", "npm run dev",
            checks, checks)
        {
            ConventionFiles = conventionFiles,
        };

        var outcome = ConfigProfileWriter.Apply(LoadableDotnetConfig, profile, force: true);
        Assert.True(outcome.Changed, outcome.SkipReason);
        var rendered = outcome.NewText!;
        Assert.Contains("convention_files = [", rendered);

        // Sanity: the rendered TOML re-parses cleanly via Tomlyn (escaping is valid).
        Assert.NotNull(TomlSerializer.Deserialize<TomlTable>(rendered));

        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        var path = Path.Combine(tmpDir, "config.toml");
        try
        {
            File.WriteAllText(path, rendered);
            var config = BuildConfigLoader.Load(path, warnSink: _ => { });
            Assert.Equal(conventionFiles, config.Project.ConventionFiles);
        }
        finally
        {
            File.Delete(path);
            Directory.Delete(tmpDir, recursive: true);
        }
    }

    // Apply into a config WITHOUT a [project] section appends one carrying the bundle.
    [Fact]
    public void ConventionFiles_AppendedWhenNoProjectSection()
    {
        var noProject = LoadableDotnetConfig[..LoadableDotnetConfig.IndexOf("[project]")].TrimEnd();
        var checks = new[] { new ProfileCheck("build", "npm", new[] { "run", "build" }, 5) };
        var profile = new ProjectProfile(
            "typescript", "react-vite", "npm",
            "npm install", "npm run build", "npm test", "npm run dev",
            checks, checks)
        {
            ConventionFiles = new[] { "conftest.py" },
        };

        var rendered = ConfigProfileWriter.Apply(noProject, profile, force: true).NewText!;
        Assert.Contains("[project]", rendered);
        Assert.Contains("convention_files = [\"conftest.py\"]", rendered);
        Assert.NotNull(TomlSerializer.Deserialize<TomlTable>(rendered));
    }

    // Empty bundle writes no convention_files line (no `convention_files = []` noise).
    [Fact]
    public void ConventionFiles_EmptyBundle_WritesNoLine()
    {
        var rendered = ConfigProfileWriter.Apply(LoadableDotnetConfig, NpmProfile(), force: true).NewText!;
        Assert.DoesNotContain("convention_files", rendered);
    }

    // A derived advisory check (lint/format) renders role = "advisory" and round-trips through the
    // real Config loader to CheckRole.Advisory, so the gate never hard-fails on it; a gating check
    // renders role = "gating" explicitly. This is the produce-side fix for op-30 (lint/format are
    // never hard gates) - the gate already honors Role, but the role was being dropped before config.
    [Fact]
    public void CheckRole_RendersAndRoundTripsThroughConfigLoad()
    {
        var checks = new[]
        {
            new ProfileCheck("build", "npm", new[] { "run", "build" }, 5),
            new ProfileCheck("lint", "npm", new[] { "run", "lint" }, 5, Role: CheckRole.Advisory),
        };
        var profile = new ProjectProfile(
            "typescript", "react-vite", "npm",
            "npm install", "npm run build", "npm test", "npm run dev",
            checks, checks);

        var outcome = ConfigProfileWriter.Apply(LoadableDotnetConfig, profile, force: true);
        Assert.True(outcome.Changed, outcome.SkipReason);
        var rendered = outcome.NewText!;

        Assert.Contains("role = \"gating\"", rendered);
        Assert.Contains("role = \"advisory\"", rendered);
        Assert.NotNull(TomlSerializer.Deserialize<TomlTable>(rendered));

        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        var path = Path.Combine(tmpDir, "config.toml");
        try
        {
            File.WriteAllText(path, rendered);
            var config = BuildConfigLoader.Load(path, warnSink: _ => { });

            Assert.Equal(2, config.Review.Checks.Count);
            var build = config.Review.Checks.Single(c => c.Name == "build");
            var lint = config.Review.Checks.Single(c => c.Name == "lint");
            Assert.Equal(CheckRole.Gating, build.Role);
            Assert.Equal(CheckRole.Advisory, lint.Role);

            // The same advisory check rode into the ship regression set and must survive there too.
            Assert.Equal(CheckRole.Advisory, config.Ship.RegressionChecks.Single(c => c.Name == "lint").Role);
        }
        finally
        {
            File.Delete(path);
            Directory.Delete(tmpDir, recursive: true);
        }
    }

    // TLB-523: a derived setup step renders role = "setup" and round-trips through the real Config
    // loader to CheckRole.Setup (a prerequisite codegen/install step run before the gating checks).
    [Fact]
    public void CheckRole_Setup_RendersAndRoundTripsThroughConfigLoad()
    {
        var checks = new[]
        {
            new ProfileCheck("xcodegen", "xcodegen", new[] { "generate" }, 2, Role: CheckRole.Setup),
            new ProfileCheck("build", "xcodebuild", Array.Empty<string>(), 5),
        };
        var profile = new ProjectProfile(
            "swift", "ios", "xcodegen",
            "brew install xcodegen", "xcodebuild build", "xcodebuild test", "",
            checks, checks);

        var outcome = ConfigProfileWriter.Apply(LoadableDotnetConfig, profile, force: true);
        Assert.True(outcome.Changed, outcome.SkipReason);
        var rendered = outcome.NewText!;
        Assert.Contains("role = \"setup\"", rendered);
        Assert.NotNull(TomlSerializer.Deserialize<TomlTable>(rendered));

        var tmpDir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(tmpDir);
        var path = Path.Combine(tmpDir, "config.toml");
        try
        {
            File.WriteAllText(path, rendered);
            var config = BuildConfigLoader.Load(path, warnSink: _ => { });
            Assert.Equal(CheckRole.Setup, config.Review.Checks.Single(c => c.Name == "xcodegen").Role);
        }
        finally
        {
            File.Delete(path);
            Directory.Delete(tmpDir, recursive: true);
        }
    }
}
